# Generated by Django 5.2.4 on 2025-10-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_studentprofile_placement_readiness_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="cluster_id",
            field=models.CharField(
                default="Unclassified", max_length=50, verbose_name="ML Cluster"
            ),
        ),
    ]
